version: "3.8"

services:
  app:
    image: node:18
    container_name: pip-installer-frontend
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c 'npm install && npm run build && npm run start'
    restart: always
    ports:
      - 3000:3000
    environment:
      - PIP_SERVER_USERNAME
      - PIP_SERVER_PASSWORD
